### ISSUE TITLE
Using deploy.sh does not create all the resources in the proper namespace

### ISSUE THREAD

**Issue by steinrh** [open-cluster-management/policy-collection#194]
We are using  the script deploy.sh, it creates a file named resources.yaml on which you can find the channel and subscription. 

Once you kubectl apply -f resources.yaml (after applying customize) it creates the channel, the subscription, the policies but somehow it does not create the policybindings and the placementrules.  

The script deletes the resources.yaml and after running  again the script avoiding the kubectl kustomize command and the deletion of the file. 

Manually the command brings the same results.

**Comment by dhaiducek** [comment]
The `deploy.sh` script should only create a Subscription and Channel and then GitOps pulls in the Policies, PlacementRules, and PlacementBindings, so it sounds like there might be an issue on the RHACM cluster itself. Does that sound right based on what you're seeing? Is there a status in the Subscription that was created that indicates an issue?

**Comment by ch-stark** [comment]
@steinrh we found some policies in not correct namespace and already sent a PR. Please note that there are a few policies where we assigned some example namespaces which need to be customized before using them this is also the idea behind:
- fork repo
- review policies you need and disable, remove others
- modify policies to you need
- set Subscription-Admin in 2.4 (it's documented in latest PR)
- apply policies via script

**Comment by gparvin** [comment]
To view the subscription resource, run a command like: `oc get subscription -n governance grc-sub -o yaml`
If there's a problem with some resources being deployed, the `status` information in the output of your command similar to 
the one above should help point us in the right direction.  I'm going to close this for now, but please re-open if you're still
having issues.
